apiVersion: v1
kind: Namespace
metadata:
  name: lab3

---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: react
  labels:
    app: react
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
        - name: react
          image: ifilyaninitmo/itdt-contained-frontend:master
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: reactapp
                  key: REACT_APP_USERNAME
            - name: REACT_APP_COMPANY_NAME
              valueFrom:
                configMapKeyRef:
                  name: reactapp
                  key: REACT_APP_COMPANY_NAME

---
apiVersion: v1
kind: Service
metadata:
  name: service-lab3
  namespace: lab3
spec:
  selector:
    app: react
  ports:
    - port: 3000
      protocol: TCP
      name: http
  type: NodePort